version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sunmi-pos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sunmi_pos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DOCKER_ENV: 'true'
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local